/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansProduto;
import modeloBeans.ModeloTabela;
import modeloConnection.ConexaoBD;
import modeloDao.DaoProduto;

/**
 *
 * @author abdiassantos
 */
public class TelaEstoque extends javax.swing.JFrame {

    BeansProduto mod = new BeansProduto();
    ConexaoBD conex = new ConexaoBD();
    DaoProduto control = new DaoProduto();
    
    int flag = 0;
    
    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
        
        preencherTabelaProdutos("select *from estoqueproduto order by nomeproduto");
        
        jTextFieldNomeProduto.setEnabled(false);
        jTextFieldPesquisarProduto.setEnabled(true);
        jComboBoxTamanhoProduto.setEnabled(false);
        jTextFieldValorProduto.setEnabled(false);
        jSpinnerQuantidadeProduto.setEnabled(false);
        jTextPaneDescricaoProduto.setEnabled(false);
        
        jButtonNovoProduto.setEnabled(true);
        jButtonSalvarProduto.setEnabled(false);
        jButtonEditarProduto.setEnabled(false);
        jButtonExcluirProduto.setEnabled(false);
        jButtonlimparCampos.setEnabled(false);
        jButtonSair.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutoEstoque = new javax.swing.JTable();
        jButtonPesquisarProduto = new javax.swing.JButton();
        jTextFieldPesquisarProduto = new javax.swing.JTextField();
        jLabelInformacoesProduto = new javax.swing.JLabel();
        jLabelIdProduto = new javax.swing.JLabel();
        jTextFieldIdProduto = new javax.swing.JTextField();
        jLabelNomeProduto = new javax.swing.JLabel();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jLabelTamanhoProduto = new javax.swing.JLabel();
        jComboBoxTamanhoProduto = new javax.swing.JComboBox();
        jLabelValorProduto = new javax.swing.JLabel();
        jLabelQuantidadeProduto = new javax.swing.JLabel();
        jSpinnerQuantidadeProduto = new javax.swing.JSpinner();
        jLabelDescricaoProduto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneDescricaoProduto = new javax.swing.JTextPane();
        jButtonNovoProduto = new javax.swing.JButton();
        jButtonSalvarProduto = new javax.swing.JButton();
        jButtonEditarProduto = new javax.swing.JButton();
        jButtonExcluirProduto = new javax.swing.JButton();
        jButtonlimparCampos = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jTextFieldValorProduto = new javax.swing.JTextField();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableProdutoEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProdutoEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutoEstoque);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(482, 80, 470, 460);

        jButtonPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButtonPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisarProduto);
        jButtonPesquisarProduto.setBounds(560, 10, 60, 60);

        jTextFieldPesquisarProduto.setToolTipText("Insira um texto para pesquisar por um produto");
        jTextFieldPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisarProduto);
        jTextFieldPesquisarProduto.setBounds(640, 30, 240, 30);

        jLabelInformacoesProduto.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelInformacoesProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produto.png"))); // NOI18N
        jLabelInformacoesProduto.setText("INFORMAÇÕES DO PRODUTO");
        getContentPane().add(jLabelInformacoesProduto);
        jLabelInformacoesProduto.setBounds(10, 10, 500, 90);

        jLabelIdProduto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabelIdProduto.setText("ID:");
        getContentPane().add(jLabelIdProduto);
        jLabelIdProduto.setBounds(10, 120, 40, 30);

        jTextFieldIdProduto.setEditable(false);
        jTextFieldIdProduto.setToolTipText("ID do produto");
        getContentPane().add(jTextFieldIdProduto);
        jTextFieldIdProduto.setBounds(50, 120, 90, 30);

        jLabelNomeProduto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabelNomeProduto.setText("Nome:");
        getContentPane().add(jLabelNomeProduto);
        jLabelNomeProduto.setBounds(170, 120, 70, 30);

        jTextFieldNomeProduto.setToolTipText("Insira aqui o nome do produto");
        getContentPane().add(jTextFieldNomeProduto);
        jTextFieldNomeProduto.setBounds(240, 120, 210, 30);

        jLabelTamanhoProduto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabelTamanhoProduto.setText("Tamanho:");
        getContentPane().add(jLabelTamanhoProduto);
        jLabelTamanhoProduto.setBounds(10, 170, 90, 30);

        jComboBoxTamanhoProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Único", "PP", "P", "M", "G", "GG", "PP - Baby Look", "P - Baby Look", "M - Baby Look", "G - Baby Look", "GG - Baby Look", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "10 Anos", "12 Anos", "14 Anos", "16 Anos", " " }));
        jComboBoxTamanhoProduto.setToolTipText("Selecione o tamanho do produto");
        getContentPane().add(jComboBoxTamanhoProduto);
        jComboBoxTamanhoProduto.setBounds(100, 170, 130, 30);

        jLabelValorProduto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabelValorProduto.setText("Valor:");
        getContentPane().add(jLabelValorProduto);
        jLabelValorProduto.setBounds(250, 170, 60, 30);

        jLabelQuantidadeProduto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabelQuantidadeProduto.setText("Quantidade:");
        getContentPane().add(jLabelQuantidadeProduto);
        jLabelQuantidadeProduto.setBounds(10, 220, 110, 30);

        jSpinnerQuantidadeProduto.setToolTipText("Insira a quantidade deste produto em estoque");
        getContentPane().add(jSpinnerQuantidadeProduto);
        jSpinnerQuantidadeProduto.setBounds(120, 220, 80, 30);

        jLabelDescricaoProduto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabelDescricaoProduto.setText("Descrição:");
        getContentPane().add(jLabelDescricaoProduto);
        jLabelDescricaoProduto.setBounds(10, 260, 110, 40);

        jTextPaneDescricaoProduto.setToolTipText("Insira aqui a descrição do produto");
        jScrollPane2.setViewportView(jTextPaneDescricaoProduto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(120, 260, 330, 150);

        jButtonNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        jButtonNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovoProduto);
        jButtonNovoProduto.setBounds(40, 490, 50, 50);

        jButtonSalvarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        jButtonSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarProduto);
        jButtonSalvarProduto.setBounds(110, 490, 50, 50);

        jButtonEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        jButtonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarProduto);
        jButtonEditarProduto.setBounds(180, 490, 50, 50);

        jButtonExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        jButtonExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirProduto);
        jButtonExcluirProduto.setBounds(250, 490, 50, 50);

        jButtonlimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar.png"))); // NOI18N
        jButtonlimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlimparCamposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonlimparCampos);
        jButtonlimparCampos.setBounds(320, 490, 50, 50);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(390, 490, 50, 50);

        jTextFieldValorProduto.setToolTipText("Insira o valor do produto");
        jTextFieldValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldValorProduto);
        jTextFieldValorProduto.setBounds(310, 170, 140, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_com_degrade.jpeg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-20, -10, 1060, 580);

        setSize(new java.awt.Dimension(979, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoProdutoActionPerformed
        flag = 1;
        
        jTextFieldIdProduto.setText("");
        jTextFieldNomeProduto.setText("");
        jTextFieldValorProduto.setText("");
        jSpinnerQuantidadeProduto.setValue(0);
        jTextPaneDescricaoProduto.setText("");
        jTextFieldPesquisarProduto.setText("");
        
        jTextFieldNomeProduto.setEnabled(true);
        jTextFieldPesquisarProduto.setEnabled(false);
        jComboBoxTamanhoProduto.setEnabled(true);
        jTextFieldValorProduto.setEnabled(true);
        jSpinnerQuantidadeProduto.setEnabled(true);
        jTextPaneDescricaoProduto.setEnabled(true);
        
        jButtonNovoProduto.setEnabled(false);
        jButtonSalvarProduto.setEnabled(true);
        jButtonEditarProduto.setEnabled(false);
        jButtonExcluirProduto.setEnabled(false);
        jButtonlimparCampos.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoProdutoActionPerformed

    private void jButtonSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarProdutoActionPerformed
        if(flag == 1){
            mod.setNomeProduto(jTextFieldNomeProduto.getText());
            mod.setTamanhoProduto((String)jComboBoxTamanhoProduto.getSelectedItem());
            mod.setValorProduto(Double.parseDouble(jTextFieldValorProduto.getText()));
            mod.setQuantidadeProduto((int) jSpinnerQuantidadeProduto.getValue());
            mod.setDescricaoProduto(jTextPaneDescricaoProduto.getText());
            
            control.SalvarProduto(mod);
            
            jTextFieldIdProduto.setText("");
            jTextFieldNomeProduto.setText("");
            jTextFieldValorProduto.setText("");
            jSpinnerQuantidadeProduto.setValue(0);
            jTextPaneDescricaoProduto.setText("");
            jTextFieldPesquisarProduto.setText("");
            
            jTextFieldNomeProduto.setEnabled(false);
            jTextFieldPesquisarProduto.setEnabled(true);
            jComboBoxTamanhoProduto.setEnabled(false);
            jTextFieldValorProduto.setEnabled(false);
            jSpinnerQuantidadeProduto.setEnabled(false);
            jTextPaneDescricaoProduto.setEnabled(false);
            
            jButtonNovoProduto.setEnabled(true);
            jButtonSalvarProduto.setEnabled(false);
            jButtonEditarProduto.setEnabled(false);
            jButtonExcluirProduto.setEnabled(false);
            jButtonlimparCampos.setEnabled(false);
            jButtonSair.setEnabled(true);
            jButtonPesquisarProduto.setEnabled(true);
            
            preencherTabelaProdutos("select *from estoqueproduto order by nomeproduto");

        }
        else if(flag == 2){
            mod.setNomeProduto(jTextFieldNomeProduto.getText());
            mod.setTamanhoProduto((String)jComboBoxTamanhoProduto.getSelectedItem());
            mod.setValorProduto(Double.parseDouble(jTextFieldValorProduto.getText()));
            mod.setQuantidadeProduto((int) jSpinnerQuantidadeProduto.getValue());
            mod.setDescricaoProduto(jTextPaneDescricaoProduto.getText());
            
            control.EditarProduto(mod);
            
            jTextFieldIdProduto.setText("");
            jTextFieldNomeProduto.setText("");
            jTextFieldValorProduto.setText("");
            jSpinnerQuantidadeProduto.setValue(0);
            jTextPaneDescricaoProduto.setText("");
            jTextFieldPesquisarProduto.setText("");
            
            jTextFieldNomeProduto.setEnabled(false);
            jTextFieldPesquisarProduto.setEnabled(true);
            jComboBoxTamanhoProduto.setEnabled(false);
            jTextFieldValorProduto.setEnabled(false);
            jSpinnerQuantidadeProduto.setEnabled(false);
            jTextPaneDescricaoProduto.setEnabled(false);
            
            jButtonNovoProduto.setEnabled(true);
            jButtonSalvarProduto.setEnabled(false);
            jButtonEditarProduto.setEnabled(false);
            jButtonExcluirProduto.setEnabled(false);
            jButtonlimparCampos.setEnabled(false);
            jButtonSair.setEnabled(true);
            jButtonPesquisarProduto.setEnabled(true);
            
            preencherTabelaProdutos("select *from estoqueproduto order by nomeproduto");
        }
    }//GEN-LAST:event_jButtonSalvarProdutoActionPerformed

    private void jTextFieldValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorProdutoActionPerformed

    private void jButtonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProdutoActionPerformed
        flag = 2;
        
        jTextFieldNomeProduto.setEnabled(true);
        jTextFieldPesquisarProduto.setEnabled(false);
        jComboBoxTamanhoProduto.setEnabled(true);
        jTextFieldValorProduto.setEnabled(true);
        jSpinnerQuantidadeProduto.setEnabled(true);
        jTextPaneDescricaoProduto.setEnabled(true);
        
        jButtonNovoProduto.setEnabled(false);
        jButtonEditarProduto.setEnabled(false);
        jButtonSalvarProduto.setEnabled(true);
        jButtonExcluirProduto.setEnabled(false);
        jButtonlimparCampos.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarProdutoActionPerformed

    private void jTableProdutoEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoEstoqueMouseClicked
        String nomeproduto = "" + jTableProdutoEstoque.getValueAt(jTableProdutoEstoque.getSelectedRow(), 1);
        
        try {
            jTextFieldPesquisarProduto.setText(nomeproduto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados\nErro: " + ex);
        }
        
        jButtonNovoProduto.setEnabled(true);
        jButtonEditarProduto.setEnabled(false);
        jButtonSalvarProduto.setEnabled(false);
        jButtonExcluirProduto.setEnabled(false);
        jButtonlimparCampos.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(true);
    }//GEN-LAST:event_jTableProdutoEstoqueMouseClicked

    private void jButtonPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarProdutoActionPerformed
        mod.setPesquisaProduto(jTextFieldPesquisarProduto.getText());
        BeansProduto model = control.BuscaProduto(mod);
        jTextFieldIdProduto.setText(String.valueOf(model.getIdProduto()));
        jTextFieldNomeProduto.setText(model.getNomeProduto());
        jComboBoxTamanhoProduto.setSelectedItem(model.getTamanhoProduto());
        jTextFieldValorProduto.setText(String.valueOf(model.getValorProduto()));
        jSpinnerQuantidadeProduto.setValue(model.getQuantidadeProduto());
        jTextPaneDescricaoProduto.setText(model.getDescricaoProduto());
       
        jTextFieldNomeProduto.setEnabled(false);
        jTextFieldPesquisarProduto.setEnabled(true);
        jComboBoxTamanhoProduto.setEnabled(false);
        jTextFieldValorProduto.setEnabled(false);
        jSpinnerQuantidadeProduto.setEnabled(false);
        jTextPaneDescricaoProduto.setEnabled(false);
        
        jButtonNovoProduto.setEnabled(true);
        jButtonSalvarProduto.setEnabled(false);
        jButtonEditarProduto.setEnabled(true);
        jButtonExcluirProduto.setEnabled(true);
        jButtonlimparCampos.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(true);
        
    }//GEN-LAST:event_jButtonPesquisarProdutoActionPerformed

    private void jButtonlimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlimparCamposActionPerformed
        jTextFieldIdProduto.setText("");
        jTextFieldNomeProduto.setText("");
        jTextFieldValorProduto.setText("");
        jSpinnerQuantidadeProduto.setValue(0);
        jTextPaneDescricaoProduto.setText("");
        jTextFieldPesquisarProduto.setText("");
            
        jTextFieldNomeProduto.setEnabled(false);
        jTextFieldPesquisarProduto.setEnabled(true);
        jComboBoxTamanhoProduto.setEnabled(false);
        jTextFieldValorProduto.setEnabled(false);
        jSpinnerQuantidadeProduto.setEnabled(false);
        jTextPaneDescricaoProduto.setEnabled(false);
        
        jButtonNovoProduto.setEnabled(true);
        jButtonSalvarProduto.setEnabled(false);
        jButtonEditarProduto.setEnabled(false);
        jButtonExcluirProduto.setEnabled(false);
        jButtonlimparCampos.setEnabled(false);
        jButtonSair.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(true);
        
        preencherTabelaProdutos("select *from estoqueproduto order by nomeproduto");

    }//GEN-LAST:event_jButtonlimparCamposActionPerformed

    private void jButtonExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirProdutoActionPerformed
        int resposta = 0;
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir os dados desse produto?!");
        
        if(resposta == JOptionPane.YES_OPTION){
            mod.setIdProduto(Integer.parseInt(jTextFieldIdProduto.getText()));
            control.ExcluirProduto(mod);
            
        jTextFieldIdProduto.setText("");
        jTextFieldNomeProduto.setText("");
        jTextFieldValorProduto.setText("");
        jSpinnerQuantidadeProduto.setValue(0);
        jTextPaneDescricaoProduto.setText("");
        jTextFieldPesquisarProduto.setText("");
        
        jTextFieldNomeProduto.setEnabled(false);
        jTextFieldPesquisarProduto.setEnabled(true);
        jComboBoxTamanhoProduto.setEnabled(false);
        jTextFieldValorProduto.setEnabled(false);
        jSpinnerQuantidadeProduto.setEnabled(false);
        jTextPaneDescricaoProduto.setEnabled(false);
        
        jButtonNovoProduto.setEnabled(true);
        jButtonSalvarProduto.setEnabled(false);
        jButtonEditarProduto.setEnabled(false);
        jButtonExcluirProduto.setEnabled(false);
        jButtonlimparCampos.setEnabled(false);
        jButtonSair.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(true);
            
        preencherTabelaProdutos("select *from estoqueproduto order by nomeproduto");

        }
        else if(resposta == JOptionPane.CANCEL_OPTION){
        jTextFieldIdProduto.setText("");
        jTextFieldNomeProduto.setText("");
        jTextFieldValorProduto.setText("");
        jSpinnerQuantidadeProduto.setValue(0);
        jTextPaneDescricaoProduto.setText("");
        jTextFieldPesquisarProduto.setText("");
        
        jTextFieldNomeProduto.setEnabled(false);
        jTextFieldPesquisarProduto.setEnabled(true);
        jComboBoxTamanhoProduto.setEnabled(false);
        jTextFieldValorProduto.setEnabled(false);
        jSpinnerQuantidadeProduto.setEnabled(false);
        jTextPaneDescricaoProduto.setEnabled(false);
        
        jButtonNovoProduto.setEnabled(true);
        jButtonSalvarProduto.setEnabled(false);
        jButtonEditarProduto.setEnabled(false);
        jButtonExcluirProduto.setEnabled(false);
        jButtonlimparCampos.setEnabled(false);
        jButtonSair.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(true);
            
        preencherTabelaProdutos("select *from estoqueproduto order by nomeproduto");
        }
    }//GEN-LAST:event_jButtonExcluirProdutoActionPerformed

    private void jTextFieldPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarProdutoActionPerformed

    public void preencherTabelaProdutos(String Sql){
        
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Valor", "Quantidade"};
        conex.conecta();
        conex.executaSql(Sql);
        
        try {
            conex.rs.first();
            do{
                dados.add(new Object[] {conex.rs.getInt("idproduto"), conex.rs.getString("nomeproduto"), 
                    conex.rs.getDouble("valorproduto"), conex.rs.getInt("quantidadeproduto")});
                
            }while(conex.rs.next());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList\n erro: " + ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableProdutoEstoque.setModel(modelo);
        jTableProdutoEstoque.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableProdutoEstoque.getColumnModel().getColumn(0).setResizable(false);
        jTableProdutoEstoque.getColumnModel().getColumn(1).setPreferredWidth(224);
        jTableProdutoEstoque.getColumnModel().getColumn(1).setResizable(false);
        jTableProdutoEstoque.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTableProdutoEstoque.getColumnModel().getColumn(2).setResizable(false);
        jTableProdutoEstoque.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableProdutoEstoque.getColumnModel().getColumn(3).setResizable(false);
        jTableProdutoEstoque.getTableHeader().setReorderingAllowed(false);
        jTableProdutoEstoque.setAutoResizeMode(jTableProdutoEstoque.AUTO_RESIZE_OFF);
        jTableProdutoEstoque.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
                
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaEstoque().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarProduto;
    private javax.swing.JButton jButtonExcluirProduto;
    private javax.swing.JButton jButtonNovoProduto;
    private javax.swing.JButton jButtonPesquisarProduto;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvarProduto;
    private javax.swing.JButton jButtonlimparCampos;
    private javax.swing.JComboBox jComboBoxTamanhoProduto;
    private javax.swing.JLabel jLabelDescricaoProduto;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelIdProduto;
    private javax.swing.JLabel jLabelInformacoesProduto;
    private javax.swing.JLabel jLabelNomeProduto;
    private javax.swing.JLabel jLabelQuantidadeProduto;
    private javax.swing.JLabel jLabelTamanhoProduto;
    private javax.swing.JLabel jLabelValorProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerQuantidadeProduto;
    private javax.swing.JTable jTableProdutoEstoque;
    private javax.swing.JTextField jTextFieldIdProduto;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldPesquisarProduto;
    private javax.swing.JTextField jTextFieldValorProduto;
    private javax.swing.JTextPane jTextPaneDescricaoProduto;
    // End of variables declaration//GEN-END:variables
}
