/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import modeloConnection.*;
/**
 *
 * @author abdiassantos
 */
public class TelaLogin extends javax.swing.JFrame {

    ConexaoBD con = new ConexaoBD();
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        con.conecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordFieldSenhaLogin = new javax.swing.JPasswordField();
        jLabelUsuarioLogin = new javax.swing.JLabel();
        jLabelSenhaLogin = new javax.swing.JLabel();
        jTextFieldUsuarioLogin = new javax.swing.JTextField();
        jButtonEntrarLogin = new javax.swing.JButton();
        jButtonSairLogin = new javax.swing.JButton();
        jButtonSobreLogin = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("HA Gerencia");
        setResizable(false);
        getContentPane().setLayout(null);

        jPasswordFieldSenhaLogin.setToolTipText("Insira Sua Senha");
        jPasswordFieldSenhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenhaLogin);
        jPasswordFieldSenhaLogin.setBounds(360, 90, 233, 40);

        jLabelUsuarioLogin.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabelUsuarioLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_login.png"))); // NOI18N
        getContentPane().add(jLabelUsuarioLogin);
        jLabelUsuarioLogin.setBounds(300, 30, 40, 40);

        jLabelSenhaLogin.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        jLabelSenhaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unlock-icon.png"))); // NOI18N
        getContentPane().add(jLabelSenhaLogin);
        jLabelSenhaLogin.setBounds(300, 90, 40, 40);

        jTextFieldUsuarioLogin.setToolTipText("Insira Seu Usuário");
        jTextFieldUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuarioLogin);
        jTextFieldUsuarioLogin.setBounds(360, 30, 233, 40);

        jButtonEntrarLogin.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButtonEntrarLogin.setText("ENTRAR");
        jButtonEntrarLogin.setToolTipText("Clique para Entrar");
        jButtonEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrarLogin);
        jButtonEntrarLogin.setBounds(420, 150, 85, 40);

        jButtonSairLogin.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButtonSairLogin.setText("SAIR");
        jButtonSairLogin.setToolTipText("Clique para Sair");
        jButtonSairLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairLoginLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairLogin);
        jButtonSairLogin.setBounds(510, 150, 85, 40);

        jButtonSobreLogin.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButtonSobreLogin.setText("SOBRE");
        jButtonSobreLogin.setToolTipText("Sobre o Desenvolvedor");
        jButtonSobreLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSobreLogin);
        jButtonSobreLogin.setBounds(270, 150, 74, 40);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpeg"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(10, 10, 250, 180);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_com_degrade.jpeg"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(-30, 0, 760, 380);

        setSize(new java.awt.Dimension(616, 237));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairLoginLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairLoginLoginActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairLoginLoginActionPerformed

    private void jTextFieldUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioLoginActionPerformed

    private void jButtonSobreLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreLoginActionPerformed
        TelaSobre telaSobreObject = new TelaSobre();
        telaSobreObject.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSobreLoginActionPerformed

    private void jButtonEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarLoginActionPerformed
        ConexaoBD conexao = new ConexaoBD();
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        TelaCriarlogin telaCriarLogin = new TelaCriarlogin();
        
        try {
            con.executaSql("select *from controleusuarioslogin where nomeusuario='"+jTextFieldUsuarioLogin.getText()+"'");
            con.rs.first();
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(jTextFieldUsuarioLogin.getText().equals("admin.sistema") && jPasswordFieldSenhaLogin.getText().equals("adminsistema")){
            int resposta = 0;
            
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Criar um Novo usuário de login no sistema?!");
            if(resposta == JOptionPane.YES_OPTION){
                conexao.conecta();
                telaCriarLogin.setVisible(true);
                this.dispose();
            }
            else if(resposta == JOptionPane.NO_OPTION){
                conexao.conecta();
                telaPrincipal.setVisible(true);
                this.dispose();
            }
            
        }
        else try {
            if(con.rs.getString("senhausuario").equals(jPasswordFieldSenhaLogin.getText())){
                telaPrincipal.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Usuário e/ou Senha Incorretos!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Usuário e/ou Senha Incorretos! \n\nErro: " + ex);
        }
    }//GEN-LAST:event_jButtonEntrarLoginActionPerformed

    private void jPasswordFieldSenhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrarLogin;
    private javax.swing.JButton jButtonSairLogin;
    private javax.swing.JButton jButtonSobreLogin;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSenhaLogin;
    private javax.swing.JLabel jLabelUsuarioLogin;
    private javax.swing.JPasswordField jPasswordFieldSenhaLogin;
    private javax.swing.JTextField jTextFieldUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
