/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modeloBeans.BeansUsuarioLogin;
import modeloConnection.ConexaoBD;
import modeloDao.DaoUsuarios;

/**
 *
 * @author abdias.neto
 */
public class TelaCriarlogin extends javax.swing.JFrame {

    DaoUsuarios control = new DaoUsuarios();
    BeansUsuarioLogin mod = new BeansUsuarioLogin();
    ConexaoBD conex = new ConexaoBD();
    
    /**
     * Creates new form TelaCriarlogin
     */
    public TelaCriarlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelusuarioLogin = new javax.swing.JLabel();
        jLabelSenhaLogin = new javax.swing.JLabel();
        jLabelEmailLogin = new javax.swing.JLabel();
        jTextFieldUsuarioLogin = new javax.swing.JTextField();
        jPasswordFieldSenhaLogin = new javax.swing.JPasswordField();
        jTextFieldEmailLogin = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("HA Gerencia");
        getContentPane().setLayout(null);

        jLabelusuarioLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelusuarioLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_login.png"))); // NOI18N
        jLabelusuarioLogin.setText("Usuário:");
        getContentPane().add(jLabelusuarioLogin);
        jLabelusuarioLogin.setBounds(50, 30, 100, 40);

        jLabelSenhaLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSenhaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unlock-icon.png"))); // NOI18N
        jLabelSenhaLogin.setText("Senha:");
        jLabelSenhaLogin.setToolTipText("");
        getContentPane().add(jLabelSenhaLogin);
        jLabelSenhaLogin.setBounds(50, 90, 100, 40);

        jLabelEmailLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEmailLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
        jLabelEmailLogin.setText("Email:");
        getContentPane().add(jLabelEmailLogin);
        jLabelEmailLogin.setBounds(50, 150, 100, 40);

        jTextFieldUsuarioLogin.setToolTipText("insisra Nome de Usuário");
        getContentPane().add(jTextFieldUsuarioLogin);
        jTextFieldUsuarioLogin.setBounds(150, 40, 150, 30);

        jPasswordFieldSenhaLogin.setToolTipText("Insira a Senha");
        getContentPane().add(jPasswordFieldSenhaLogin);
        jPasswordFieldSenhaLogin.setBounds(150, 100, 150, 30);

        jTextFieldEmailLogin.setToolTipText("Insira seu Email");
        getContentPane().add(jTextFieldEmailLogin);
        jTextFieldEmailLogin.setBounds(150, 160, 150, 30);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(60, 220, 60, 60);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(210, 220, 60, 60);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_sem_degrade.jpeg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-20, -30, 400, 430);

        setSize(new java.awt.Dimension(341, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        
        this.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        
        mod.setUsuarioLogin(jTextFieldUsuarioLogin.getText());
        mod.setSenhaLogin(jPasswordFieldSenhaLogin.getText());
        mod.setEmailLogin(jTextFieldEmailLogin.getText());
        
        control.SalvarUsuario(mod);
        
        telaLogin.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaCriarlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaCriarlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaCriarlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaCriarlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaCriarlogin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelEmailLogin;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelSenhaLogin;
    private javax.swing.JLabel jLabelusuarioLogin;
    private javax.swing.JPasswordField jPasswordFieldSenhaLogin;
    private javax.swing.JTextField jTextFieldEmailLogin;
    private javax.swing.JTextField jTextFieldUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
