/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modeloBeans.BeansCliente;
import modeloBeans.ModeloTabela;
import modeloConnection.ConexaoBD;
import modeloDao.DaoCliente;

/**
 *
 * @author abdiassantos
 */
public class TelaCliente extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    DaoCliente control = new DaoCliente();
    BeansCliente mod = new BeansCliente();
    
    int flag = 0;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaCliente() {
        initComponents();
        
        //Preenche a tabela;
        preencherTabelaClientes("select *from controlecliente order by nomecliente");
        
        preencheSomaDosValores("select sum(valoratual) as ValorSomaAtual from controlecliente");
        
        //mantém os botões e fields desativados;
        jTextFieldNomeCliente.setEnabled(false);
        jFormattedTextFieldCPFCliente.setEnabled(false);
        jFormattedTextFieldTelCliente.setEnabled(false);
        jTextFieldEmailCliente.setEnabled(false);
        jTextFieldRuaCliente.setEnabled(false);
        jFormattedTextFieldNumeroCasa.setEnabled(false);
        jTextFieldBairroCliente.setEnabled(false);
        jTextFieldCidadeCliente.setEnabled(false);
        jComboBoxEstadoCliente.setEnabled(false);
        jFormattedTextFieldCEPCliente.setEnabled(false);
        jTextFieldComplementeCliente.setEnabled(false);
        jTextFieldValorDebitarCreditar.setEnabled(false);
        
        jButtonCreditar.setEnabled(false);
        jButtonDebitar.setEnabled(false);
        jButtonEditarClientes.setEnabled(false);
        jButtonExcluirClientes.setEnabled(false);
        jButtonLimparClientes.setEnabled(false);
        jButtonNovoCliente.setEnabled(true);
        jButtonPesquisarCliente.setEnabled(true);
        jButtonSalvarClientes.setEnabled(false);
        jButtonVoltarTelaCliente.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltarTelaCliente = new javax.swing.JButton();
        jLabelInformacoesPessoais = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jButtonPesquisarCliente = new javax.swing.JButton();
        jTextFieldPesquisarCliente = new javax.swing.JTextField();
        jButtonSalvarClientes = new javax.swing.JButton();
        jButtonEditarClientes = new javax.swing.JButton();
        jButtonExcluirClientes = new javax.swing.JButton();
        jButtonLimparClientes = new javax.swing.JButton();
        jLabelNomeCliente = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabelIDCliente = new javax.swing.JLabel();
        jTextFieldIDCliente = new javax.swing.JTextField();
        jLabelCPFCliente = new javax.swing.JLabel();
        jLabelTelCliente = new javax.swing.JLabel();
        jFormattedTextFieldCPFCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelCliente = new javax.swing.JFormattedTextField();
        jLabelEmailCliente = new javax.swing.JLabel();
        jTextFieldEmailCliente = new javax.swing.JTextField();
        jLabelEnderecoCliente = new javax.swing.JLabel();
        jLabelRuaCliente = new javax.swing.JLabel();
        jTextFieldRuaCliente = new javax.swing.JTextField();
        jLabelNumeroCasaCliente = new javax.swing.JLabel();
        jLabelBairroCliente = new javax.swing.JLabel();
        jTextFieldBairroCliente = new javax.swing.JTextField();
        jLabelCidadeCliente = new javax.swing.JLabel();
        jTextFieldCidadeCliente = new javax.swing.JTextField();
        jLabelEstadoCliente = new javax.swing.JLabel();
        jComboBoxEstadoCliente = new javax.swing.JComboBox();
        jLabelCEPCliente = new javax.swing.JLabel();
        jLabel3ComplementoCliente = new javax.swing.JLabel();
        jTextFieldComplementeCliente = new javax.swing.JTextField();
        jFormattedTextFieldCEPCliente = new javax.swing.JFormattedTextField();
        jLabelFinanceiro = new javax.swing.JLabel();
        jLabelValorAtual = new javax.swing.JLabel();
        jButtonCreditar = new javax.swing.JButton();
        jButtonDebitar = new javax.swing.JButton();
        jTextFieldValorAtual = new javax.swing.JTextField();
        jButtonNovoCliente = new javax.swing.JButton();
        jFormattedTextFieldNumeroCasa = new javax.swing.JFormattedTextField();
        jTextFieldValorDebitarCreditar = new javax.swing.JTextField();
        jButtonCalculadora = new javax.swing.JButton();
        jLabelSomaDosValores = new javax.swing.JLabel();
        jTextFieldSomaDosValores = new javax.swing.JTextField();
        jLabelFundoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("HA Gerencia");
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonVoltarTelaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        jButtonVoltarTelaCliente.setToolTipText("Voltar");
        jButtonVoltarTelaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarTelaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarTelaCliente);
        jButtonVoltarTelaCliente.setBounds(400, 590, 50, 50);

        jLabelInformacoesPessoais.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelInformacoesPessoais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        jLabelInformacoesPessoais.setText("INFORMAÇÕES PESSOAIS");
        getContentPane().add(jLabelInformacoesPessoais);
        jLabelInformacoesPessoais.setBounds(30, 0, 420, 70);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 80, 530, 470);

        jButtonPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButtonPesquisarCliente.setToolTipText("Pesquisar");
        jButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisarCliente);
        jButtonPesquisarCliente.setBounds(600, 10, 70, 68);

        jTextFieldPesquisarCliente.setToolTipText("Insira o Texto da sua Pesquisa");
        getContentPane().add(jTextFieldPesquisarCliente);
        jTextFieldPesquisarCliente.setBounds(690, 30, 280, 30);

        jButtonSalvarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        jButtonSalvarClientes.setToolTipText("Salvar");
        jButtonSalvarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarClientes);
        jButtonSalvarClientes.setBounds(100, 590, 50, 50);

        jButtonEditarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        jButtonEditarClientes.setToolTipText("Editar");
        jButtonEditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarClientes);
        jButtonEditarClientes.setBounds(160, 590, 50, 50);

        jButtonExcluirClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        jButtonExcluirClientes.setToolTipText("Excluir");
        jButtonExcluirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirClientes);
        jButtonExcluirClientes.setBounds(220, 590, 50, 50);

        jButtonLimparClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar.png"))); // NOI18N
        jButtonLimparClientes.setToolTipText("Limpar");
        jButtonLimparClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimparClientes);
        jButtonLimparClientes.setBounds(280, 590, 50, 50);

        jLabelNomeCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelNomeCliente.setText("NOME:");
        getContentPane().add(jLabelNomeCliente);
        jLabelNomeCliente.setBounds(130, 80, 70, 30);

        jTextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeCliente);
        jTextFieldNomeCliente.setBounds(180, 80, 300, 30);

        jLabelIDCliente.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabelIDCliente.setText("ID:");
        getContentPane().add(jLabelIDCliente);
        jLabelIDCliente.setBounds(10, 80, 30, 30);

        jTextFieldIDCliente.setEditable(false);
        getContentPane().add(jTextFieldIDCliente);
        jTextFieldIDCliente.setBounds(40, 80, 80, 30);

        jLabelCPFCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelCPFCliente.setText("CPF:");
        getContentPane().add(jLabelCPFCliente);
        jLabelCPFCliente.setBounds(10, 120, 40, 30);

        jLabelTelCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelTelCliente.setText("TEL:");
        getContentPane().add(jLabelTelCliente);
        jLabelTelCliente.setBounds(260, 120, 40, 30);

        try {
            jFormattedTextFieldCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCPFCliente);
        jFormattedTextFieldCPFCliente.setBounds(50, 120, 200, 30);

        try {
            jFormattedTextFieldTelCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldTelCliente);
        jFormattedTextFieldTelCliente.setBounds(300, 120, 180, 30);

        jLabelEmailCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelEmailCliente.setText("EMAIL:");
        getContentPane().add(jLabelEmailCliente);
        jLabelEmailCliente.setBounds(10, 160, 50, 30);
        getContentPane().add(jTextFieldEmailCliente);
        jTextFieldEmailCliente.setBounds(60, 160, 420, 30);

        jLabelEnderecoCliente.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelEnderecoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Endereco.png"))); // NOI18N
        jLabelEnderecoCliente.setText("               ENDEREÇO");
        getContentPane().add(jLabelEnderecoCliente);
        jLabelEnderecoCliente.setBounds(50, 200, 400, 60);

        jLabelRuaCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelRuaCliente.setText("RUA:");
        getContentPane().add(jLabelRuaCliente);
        jLabelRuaCliente.setBounds(10, 270, 40, 30);
        getContentPane().add(jTextFieldRuaCliente);
        jTextFieldRuaCliente.setBounds(50, 270, 310, 30);

        jLabelNumeroCasaCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelNumeroCasaCliente.setText("Nº:");
        getContentPane().add(jLabelNumeroCasaCliente);
        jLabelNumeroCasaCliente.setBounds(370, 270, 30, 30);

        jLabelBairroCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelBairroCliente.setText("BAIRRO:");
        getContentPane().add(jLabelBairroCliente);
        jLabelBairroCliente.setBounds(10, 310, 60, 30);
        getContentPane().add(jTextFieldBairroCliente);
        jTextFieldBairroCliente.setBounds(70, 310, 160, 30);

        jLabelCidadeCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelCidadeCliente.setText("CIDADE:");
        getContentPane().add(jLabelCidadeCliente);
        jLabelCidadeCliente.setBounds(240, 310, 60, 30);
        getContentPane().add(jTextFieldCidadeCliente);
        jTextFieldCidadeCliente.setBounds(300, 310, 180, 30);

        jLabelEstadoCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelEstadoCliente.setText("ESTADO:");
        getContentPane().add(jLabelEstadoCliente);
        jLabelEstadoCliente.setBounds(10, 350, 50, 30);

        jComboBoxEstadoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acre ", "Alagoas ", "Amapá ", "Amazonas ", "Bahia ", "Ceará ", "Distrito Federal ", "Espírito Santo ", "Goiás ", "Maranhão ", "Mato Grosso ", "Mato Grosso do Sul ", "Minas Gerais ", "Pará ", "Paraíba ", "Paraná ", "Pernambuco ", "Piauí ", "Rio de Janeiro\t", "Rio Grande do Norte", "Rio Grande do Sul ", "Rondônia ", "Roraima ", "Santa Catarina ", "São Paulo ", "Sergipe ", "Tocantins" }));
        getContentPane().add(jComboBoxEstadoCliente);
        jComboBoxEstadoCliente.setBounds(60, 350, 160, 30);

        jLabelCEPCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabelCEPCliente.setText("CEP:");
        getContentPane().add(jLabelCEPCliente);
        jLabelCEPCliente.setBounds(240, 350, 40, 30);

        jLabel3ComplementoCliente.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel3ComplementoCliente.setText("COMPLEMENTO:");
        getContentPane().add(jLabel3ComplementoCliente);
        jLabel3ComplementoCliente.setBounds(10, 390, 110, 30);

        jTextFieldComplementeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplementeClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldComplementeCliente);
        jTextFieldComplementeCliente.setBounds(120, 390, 360, 30);

        try {
            jFormattedTextFieldCEPCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldCEPCliente);
        jFormattedTextFieldCEPCliente.setBounds(280, 350, 200, 30);

        jLabelFinanceiro.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/financeiro.png"))); // NOI18N
        jLabelFinanceiro.setText("              FINANCEIRO");
        getContentPane().add(jLabelFinanceiro);
        jLabelFinanceiro.setBounds(50, 430, 400, 60);

        jLabelValorAtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cifrao.png"))); // NOI18N
        getContentPane().add(jLabelValorAtual);
        jLabelValorAtual.setBounds(120, 500, 40, 40);

        jButtonCreditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sacodedinheiromenos.png"))); // NOI18N
        jButtonCreditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreditar);
        jButtonCreditar.setBounds(310, 490, 50, 50);

        jButtonDebitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sacodedinheiromenosMesmo.png"))); // NOI18N
        jButtonDebitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDebitarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDebitar);
        jButtonDebitar.setBounds(380, 490, 50, 50);

        jTextFieldValorAtual.setEditable(false);
        jTextFieldValorAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorAtualActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldValorAtual);
        jTextFieldValorAtual.setBounds(70, 540, 140, 30);

        jButtonNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovoCliente);
        jButtonNovoCliente.setBounds(40, 590, 50, 50);

        try {
            jFormattedTextFieldNumeroCasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldNumeroCasa);
        jFormattedTextFieldNumeroCasa.setBounds(390, 270, 90, 30);

        jTextFieldValorDebitarCreditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorDebitarCreditarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldValorDebitarCreditar);
        jTextFieldValorDebitarCreditar.setBounds(290, 540, 160, 30);

        jButtonCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculadora.png"))); // NOI18N
        jButtonCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculadoraActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculadora);
        jButtonCalculadora.setBounds(340, 590, 50, 50);

        jLabelSomaDosValores.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelSomaDosValores.setText("Total:");
        getContentPane().add(jLabelSomaDosValores);
        jLabelSomaDosValores.setBounds(740, 590, 100, 30);

        jTextFieldSomaDosValores.setEditable(false);
        jTextFieldSomaDosValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSomaDosValoresActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSomaDosValores);
        jTextFieldSomaDosValores.setBounds(840, 590, 200, 30);

        jLabelFundoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_com_degrade.jpeg"))); // NOI18N
        getContentPane().add(jLabelFundoCliente);
        jLabelFundoCliente.setBounds(-20, 0, 1100, 710);

        setSize(new java.awt.Dimension(1070, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarTelaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarTelaClienteActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarTelaClienteActionPerformed

    private void jTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeClienteActionPerformed

    private void jFormattedTextFieldCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFClienteActionPerformed
        
    }//GEN-LAST:event_jFormattedTextFieldCPFClienteActionPerformed

    private void jTextFieldComplementeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplementeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComplementeClienteActionPerformed

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed
        flag = 1;
        
        jTextFieldIDCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jFormattedTextFieldCPFCliente.setText("");
        jFormattedTextFieldTelCliente.setText("");
        jTextFieldEmailCliente.setText("");
        jTextFieldRuaCliente.setText("");
        jFormattedTextFieldNumeroCasa.setText("");
        jTextFieldBairroCliente.setText("");
        jTextFieldCidadeCliente.setText("");
        jFormattedTextFieldCEPCliente.setText("");
        jTextFieldComplementeCliente.setText("");
        jTextFieldValorDebitarCreditar.setText("");
        jTextFieldPesquisarCliente.setText("");
        
        //Ativa os text fields para criar um novo
        jTextFieldNomeCliente.setEnabled(true);
        jFormattedTextFieldCPFCliente.setEnabled(true);
        jFormattedTextFieldTelCliente.setEnabled(true);
        jTextFieldEmailCliente.setEnabled(true);
        jTextFieldRuaCliente.setEnabled(true);
        jFormattedTextFieldNumeroCasa.setEnabled(true);
        jTextFieldBairroCliente.setEnabled(true);
        jTextFieldCidadeCliente.setEnabled(true);
        jComboBoxEstadoCliente.setEnabled(true);
        jFormattedTextFieldCEPCliente.setEnabled(true);
        jTextFieldComplementeCliente.setEnabled(true);
        jTextFieldValorDebitarCreditar.setEnabled(true);
        jTextFieldPesquisarCliente.setEnabled(false);
        
        jButtonEditarClientes.setEnabled(false);
        jButtonCreditar.setEnabled(false);
        jButtonDebitar.setEnabled(false);
        jButtonExcluirClientes.setEnabled(false);
        jButtonLimparClientes.setEnabled(true);
        jButtonNovoCliente.setEnabled(true);
        jButtonSalvarClientes.setEnabled(true);
        jButtonVoltarTelaCliente.setEnabled(true);
        jButtonPesquisarCliente.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void jButtonLimparClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparClientesActionPerformed
        //Limpa os campos dos textFields;
        jTextFieldIDCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jFormattedTextFieldCPFCliente.setText("");
        jFormattedTextFieldTelCliente.setText("");
        jTextFieldEmailCliente.setText("");
        jTextFieldRuaCliente.setText("");
        jFormattedTextFieldNumeroCasa.setText("");
        jTextFieldBairroCliente.setText("");
        jTextFieldCidadeCliente.setText("");
        jFormattedTextFieldCEPCliente.setText("");
        jTextFieldComplementeCliente.setText("");
        jTextFieldValorDebitarCreditar.setText("");
        jTextFieldPesquisarCliente.setText("");
        
        //mantém os botões e fields desativados;
        jTextFieldNomeCliente.setEnabled(false);
        jFormattedTextFieldCPFCliente.setEnabled(false);
        jFormattedTextFieldTelCliente.setEnabled(false);
        jTextFieldEmailCliente.setEnabled(false);
        jTextFieldRuaCliente.setEnabled(false);
        jFormattedTextFieldNumeroCasa.setEnabled(false);
        jTextFieldBairroCliente.setEnabled(false);
        jTextFieldCidadeCliente.setEnabled(false);
        jComboBoxEstadoCliente.setEnabled(false);
        jFormattedTextFieldCEPCliente.setEnabled(false);
        jTextFieldComplementeCliente.setEnabled(false);
        jTextFieldValorDebitarCreditar.setEnabled(false);
        jTextFieldPesquisarCliente.setEnabled(true);
        
        jButtonEditarClientes.setEnabled(false);
        jButtonCreditar.setEnabled(false);
        jButtonDebitar.setEnabled(false);
        jButtonExcluirClientes.setEnabled(false);
        jButtonLimparClientes.setEnabled(true);
        jButtonNovoCliente.setEnabled(true);
        jButtonSalvarClientes.setEnabled(false);
        jButtonVoltarTelaCliente.setEnabled(true);
        jButtonPesquisarCliente.setEnabled(true);
        
        preencherTabelaClientes("select *from controlecliente order by nomecliente");
        preencheSomaDosValores("select sum(valoratual) as ValorSomaAtual from controlecliente");
        
    }//GEN-LAST:event_jButtonLimparClientesActionPerformed

    private void jButtonSalvarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarClientesActionPerformed

        if(flag == 1){
            mod.setNomeCliente(jTextFieldNomeCliente.getText());
            mod.setCpfCliente(jFormattedTextFieldCPFCliente.getText());
            mod.setTelefoneCliente(jFormattedTextFieldTelCliente.getText());
            mod.setEmailCliente(jTextFieldEmailCliente.getText());
            mod.setRuaCliente(jTextFieldRuaCliente.getText());
            mod.setNumeroCasa(jFormattedTextFieldNumeroCasa.getText());
            mod.setBairroCliente(jTextFieldBairroCliente.getText());
            mod.setCidadeCliente(jTextFieldCidadeCliente.getText());
            mod.setEstadoCliente((String) jComboBoxEstadoCliente.getSelectedItem());
            mod.setCepCliente(jFormattedTextFieldCEPCliente.getText());
            mod.setComplementoEndereco(jTextFieldComplementeCliente.getText());
            
            control.Salvar(mod);
            
            //Limpa os campos dos textFields;
            jTextFieldIDCliente.setText("");
            jTextFieldNomeCliente.setText("");
            jFormattedTextFieldCPFCliente.setText("");
            jFormattedTextFieldTelCliente.setText("");
            jTextFieldEmailCliente.setText("");
            jTextFieldRuaCliente.setText("");
            jFormattedTextFieldNumeroCasa.setText("");
            jTextFieldBairroCliente.setText("");
            jTextFieldCidadeCliente.setText("");
            jFormattedTextFieldCEPCliente.setText("");
            jTextFieldComplementeCliente.setText("");
            jTextFieldValorDebitarCreditar.setText("");
            jTextFieldPesquisarCliente.setText("");
        
            //mantém os botões e fields desativados;
            jTextFieldNomeCliente.setEnabled(false);
            jFormattedTextFieldCPFCliente.setEnabled(false);
            jFormattedTextFieldTelCliente.setEnabled(false);
            jTextFieldEmailCliente.setEnabled(false);
            jTextFieldRuaCliente.setEnabled(false);
            jFormattedTextFieldNumeroCasa.setEnabled(false);
            jTextFieldBairroCliente.setEnabled(false);
            jTextFieldCidadeCliente.setEnabled(false);
            jComboBoxEstadoCliente.setEnabled(false);
            jFormattedTextFieldCEPCliente.setEnabled(false);
            jTextFieldComplementeCliente.setEnabled(false);
            jTextFieldValorDebitarCreditar.setEnabled(false);
            jTextFieldPesquisarCliente.setEnabled(true);
            
            jButtonNovoCliente.setEnabled(true);
            jButtonSalvarClientes.setEnabled(false);
            jButtonEditarClientes.setEnabled(false);
            jButtonExcluirClientes.setEnabled(false);
            jButtonLimparClientes.setEnabled(false);
            jButtonPesquisarCliente.setEnabled(true);
            jButtonVoltarTelaCliente.setEnabled(true);
            
            preencherTabelaClientes("select *from controlecliente order by nomecliente");
            preencheSomaDosValores("select sum(valoratual) as ValorSomaAtual from controlecliente");
            
        }
        else if(flag == 2){
            
            mod.setNomeCliente(jTextFieldNomeCliente.getText());
            mod.setCpfCliente(jFormattedTextFieldCPFCliente.getText());
            mod.setTelefoneCliente(jFormattedTextFieldTelCliente.getText());
            mod.setEmailCliente(jTextFieldEmailCliente.getText());
            mod.setRuaCliente(jTextFieldRuaCliente.getText());
            mod.setNumeroCasa(jFormattedTextFieldNumeroCasa.getText());
            mod.setBairroCliente(jTextFieldBairroCliente.getText());
            mod.setCidadeCliente(jTextFieldCidadeCliente.getText());
            mod.setEstadoCliente((String) jComboBoxEstadoCliente.getSelectedItem());
            mod.setCepCliente(jFormattedTextFieldCEPCliente.getText());
            mod.setComplementoEndereco(jTextFieldComplementeCliente.getText());
            
            control.EditarCliente(mod);
            
            //Limpa os campos dos textFields;
            jTextFieldIDCliente.setText("");
            jTextFieldNomeCliente.setText("");
            jFormattedTextFieldCPFCliente.setText("");
            jFormattedTextFieldTelCliente.setText("");
            jTextFieldEmailCliente.setText("");
            jTextFieldRuaCliente.setText("");
            jFormattedTextFieldNumeroCasa.setText("");
            jTextFieldBairroCliente.setText("");
            jTextFieldCidadeCliente.setText("");
            jFormattedTextFieldCEPCliente.setText("");
            jTextFieldComplementeCliente.setText("");
            jTextFieldValorDebitarCreditar.setText("");
            jTextFieldPesquisarCliente.setText("");
        
            //mantém os botões e fields desativados;
            jTextFieldNomeCliente.setEnabled(false);
            jFormattedTextFieldCPFCliente.setEnabled(false);
            jFormattedTextFieldTelCliente.setEnabled(false);
            jTextFieldEmailCliente.setEnabled(false);
            jTextFieldRuaCliente.setEnabled(false);
            jFormattedTextFieldNumeroCasa.setEnabled(false);
            jTextFieldBairroCliente.setEnabled(false);
            jTextFieldCidadeCliente.setEnabled(false);
            jComboBoxEstadoCliente.setEnabled(false);
            jFormattedTextFieldCEPCliente.setEnabled(false);
            jTextFieldComplementeCliente.setEnabled(false);
            jTextFieldValorDebitarCreditar.setEnabled(false);
            jTextFieldPesquisarCliente.setEnabled(true);
            
            jButtonNovoCliente.setEnabled(true);
            jButtonSalvarClientes.setEnabled(false);
            jButtonEditarClientes.setEnabled(false);
            jButtonExcluirClientes.setEnabled(false);
            jButtonLimparClientes.setEnabled(false);
            jButtonPesquisarCliente.setEnabled(true);
            jButtonVoltarTelaCliente.setEnabled(true);
            
            preencherTabelaClientes("select *from controlecliente order by nomecliente");
            preencheSomaDosValores("select sum(valoratual) as ValorSomaAtual from controlecliente");

        }
    }//GEN-LAST:event_jButtonSalvarClientesActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
       
        String nomecliente = "" + jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 1);
        
        try {
            jTextFieldPesquisarCliente.setText(nomecliente);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados\nErro: " + ex);
        }
        
        conex.desconecta();
        jTextFieldValorDebitarCreditar.setEnabled(false);
        jButtonCreditar.setEnabled(false);
        jButtonDebitar.setEnabled(false);
        jButtonEditarClientes.setEnabled(false);
        jButtonExcluirClientes.setEnabled(false);
        jButtonLimparClientes.setEnabled(false);
        
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarClienteActionPerformed
        
        mod.setPesquisa(jTextFieldPesquisarCliente.getText());
        BeansCliente model = control.buscaCliente(mod);
        jTextFieldIDCliente.setText(String.valueOf(model.getIdCliente()));
        jTextFieldNomeCliente.setText(model.getNomeCliente());
        jFormattedTextFieldCPFCliente.setText(model.getCpfCliente());
        jFormattedTextFieldTelCliente.setText(model.getTelefoneCliente());
        jTextFieldEmailCliente.setText(model.getEmailCliente());
        jTextFieldRuaCliente.setText(model.getRuaCliente());
        jFormattedTextFieldNumeroCasa.setText(model.getNumeroCasa());
        jTextFieldBairroCliente.setText(model.getBairroCliente());
        jTextFieldCidadeCliente.setText(model.getCidadeCliente());
        jComboBoxEstadoCliente.setSelectedItem(model.getEstadoCliente());
        jFormattedTextFieldCEPCliente.setText(model.getCepCliente());
        jTextFieldComplementeCliente.setText(model.getComplementoEndereco());
        jTextFieldValorAtual.setText(String.valueOf(model.getValorAtual()));
        
        jTextFieldValorDebitarCreditar.setEnabled(true);
        jButtonCreditar.setEnabled(true);
        jButtonDebitar.setEnabled(true);
        jButtonEditarClientes.setEnabled(true);
        jButtonExcluirClientes.setEnabled(true);
        jButtonLimparClientes.setEnabled(true);
        
    }//GEN-LAST:event_jButtonPesquisarClienteActionPerformed

    private void jButtonEditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarClientesActionPerformed
        flag = 2;
        
        //Ativa os text fields para criar um novo
        jTextFieldNomeCliente.setEnabled(true);
        jFormattedTextFieldCPFCliente.setEnabled(true);
        jFormattedTextFieldTelCliente.setEnabled(true);
        jTextFieldEmailCliente.setEnabled(true);
        jTextFieldRuaCliente.setEnabled(true);
        jFormattedTextFieldNumeroCasa.setEnabled(true);
        jTextFieldBairroCliente.setEnabled(true);
        jTextFieldCidadeCliente.setEnabled(true);
        jComboBoxEstadoCliente.setEnabled(true);
        jFormattedTextFieldCEPCliente.setEnabled(true);
        jTextFieldComplementeCliente.setEnabled(true);
        jTextFieldValorDebitarCreditar.setEnabled(true);
        
        jButtonCreditar.setEnabled(false);
        jButtonDebitar.setEnabled(false);
        jButtonLimparClientes.setEnabled(true);
        jButtonVoltarTelaCliente.setEnabled(true);
        jButtonSalvarClientes.setEnabled(true);
        
    }//GEN-LAST:event_jButtonEditarClientesActionPerformed

    private void jButtonExcluirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirClientesActionPerformed
        int resposta = 0;
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir os dados desse cliente?!");
        
        if(resposta == JOptionPane.YES_OPTION){
            mod.setIdCliente(Integer.parseInt(jTextFieldIDCliente.getText()));
            control.excluirCliente(mod);
            
            jTextFieldIDCliente.setText("");
            jTextFieldNomeCliente.setText("");
            jFormattedTextFieldCPFCliente.setText("");
            jFormattedTextFieldTelCliente.setText("");
            jTextFieldEmailCliente.setText("");
            jTextFieldRuaCliente.setText("");
            jFormattedTextFieldNumeroCasa.setText("");
            jTextFieldBairroCliente.setText("");
            jTextFieldCidadeCliente.setText("");
            jFormattedTextFieldCEPCliente.setText("");
            jTextFieldComplementeCliente.setText("");
            jTextFieldValorDebitarCreditar.setText("");
            jTextFieldValorAtual.setText("");
            
            jButtonNovoCliente.setEnabled(true);
            jButtonEditarClientes.setEnabled(false);
            jButtonExcluirClientes.setEnabled(false);
            jButtonSalvarClientes.setEnabled(false);
            jButtonLimparClientes.setEnabled(false);
            jButtonCreditar.setEnabled(false);
            jButtonDebitar.setEnabled(false);
            
            preencherTabelaClientes("select *from controlecliente order by nomecliente");
            preencheSomaDosValores("select sum(valoratual) as ValorSomaAtual from controlecliente");

        }
        else if(resposta == JOptionPane.CANCEL_OPTION){
            jTextFieldIDCliente.setText("");
            jTextFieldNomeCliente.setText("");
            jFormattedTextFieldCPFCliente.setText("");
            jFormattedTextFieldTelCliente.setText("");
            jTextFieldEmailCliente.setText("");
            jTextFieldRuaCliente.setText("");
            jFormattedTextFieldNumeroCasa.setText("");
            jTextFieldBairroCliente.setText("");
            jTextFieldCidadeCliente.setText("");
            jFormattedTextFieldCEPCliente.setText("");
            jTextFieldComplementeCliente.setText("");
            jTextFieldValorDebitarCreditar.setText("");
            jTextFieldValorAtual.setText("");
            
            jButtonNovoCliente.setEnabled(true);
            jButtonEditarClientes.setEnabled(false);
            jButtonExcluirClientes.setEnabled(false);
            jButtonSalvarClientes.setEnabled(false);
            jButtonLimparClientes.setEnabled(false);
            jButtonCreditar.setEnabled(false);
            jButtonDebitar.setEnabled(false);
            
            preencherTabelaClientes("select *from controlecliente order by nomecliente");
            preencheSomaDosValores("select sum(valoratual) as ValorSomaAtual from controlecliente");
        }
    }//GEN-LAST:event_jButtonExcluirClientesActionPerformed

    private void jButtonCreditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditarActionPerformed
        double creditarValor;
        double valorAtualDB;
        
        valorAtualDB = Double.parseDouble(jTextFieldValorAtual.getText());
        creditarValor = Double.parseDouble(jTextFieldValorDebitarCreditar.getText());
        
        valorAtualDB = valorAtualDB + creditarValor;
        
        jTextFieldValorAtual.setText(String.valueOf(valorAtualDB));
        
        mod.setValorAtual(Double.parseDouble(jTextFieldValorAtual.getText()));
            
        control.AtualizaValorAtual(mod);
        
        preencherTabelaClientes("select *from controlecliente order by nomecliente");
        preencheSomaDosValores("select sum(valoratual) as ValorSomaAtual from controlecliente");
        
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "O cliente executou uma devolução?!");
        
        if(resposta == JOptionPane.YES_OPTION){
            TelaReduzirEstoque telaReduzirEstoque = new TelaReduzirEstoque();
        
            telaReduzirEstoque.setVisible(true);
            this.dispose();
        }
        else{
            jTextFieldValorDebitarCreditar.setText("");
        }
        
    }//GEN-LAST:event_jButtonCreditarActionPerformed

    private void jTextFieldValorDebitarCreditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorDebitarCreditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorDebitarCreditarActionPerformed

    private void jButtonDebitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDebitarActionPerformed
        double creditarValor;
        double valorAtualDB;
        
        valorAtualDB = Double.parseDouble(jTextFieldValorAtual.getText());
        creditarValor = Double.parseDouble(jTextFieldValorDebitarCreditar.getText());
        
        valorAtualDB = valorAtualDB - creditarValor;
        
        jTextFieldValorAtual.setText(String.valueOf(valorAtualDB));
        
        mod.setValorAtual(Double.parseDouble(jTextFieldValorAtual.getText()));
            
        control.AtualizaValorAtual(mod);
        
        preencherTabelaClientes("select *from controlecliente order by nomecliente");
        preencheSomaDosValores("select sum(valoratual) as ValorSomaAtual from controlecliente");
        
        TelaReduzirEstoque telaReduzirEstoque = new TelaReduzirEstoque();
        
        telaReduzirEstoque.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonDebitarActionPerformed

    private void jButtonCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculadoraActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Desejas Abrir a Calculadora?");
        
        if(resposta == JOptionPane.YES_OPTION){
            try {
                Runtime.getRuntime().exec("cmd.exe /C start calc.exe");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro: \n" + ex);
            }
        }
    }//GEN-LAST:event_jButtonCalculadoraActionPerformed

    private void jTextFieldValorAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorAtualActionPerformed

    private void jTextFieldSomaDosValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSomaDosValoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSomaDosValoresActionPerformed

    public void preencherTabelaClientes(String Sql){
        
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Valor Atual", "CPF"};
        conex.conecta();
        conex.executaSql(Sql);
        
        try {
            conex.rs.first();
            do{
                dados.add(new Object[] {conex.rs.getInt("idcliente"), conex.rs.getString("nomecliente"), conex.rs.getDouble("valoratual"), conex.rs.getString("cpfcliente")});
            }while(conex.rs.next());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList\n erro: " + ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableCliente.setModel(modelo);
        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableCliente.getColumnModel().getColumn(0).setResizable(false);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(224);
        jTableCliente.getColumnModel().getColumn(1).setResizable(false);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableCliente.getColumnModel().getColumn(2).setResizable(false);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableCliente.getColumnModel().getColumn(3).setResizable(false);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);
        jTableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
        
        
                
    }
    
    public void preencheSomaDosValores(String SQL){
        double somaDosValoresAtuais = 0;
        
        conex.conecta();
        conex.executaSql(SQL);
        
        try {
            conex.rs.first();
            do {
                somaDosValoresAtuais = somaDosValoresAtuais + conex.rs.getDouble("ValorSomaAtual");
            } while (conex.rs.next());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher a Soma dos Valores Atuais! \nErro: " + ex);
        }
        
        jTextFieldSomaDosValores.setText(String.valueOf(somaDosValoresAtuais));
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaCliente().setVisible(true);
//            }
//        });
//    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculadora;
    private javax.swing.JButton jButtonCreditar;
    private javax.swing.JButton jButtonDebitar;
    private javax.swing.JButton jButtonEditarClientes;
    private javax.swing.JButton jButtonExcluirClientes;
    private javax.swing.JButton jButtonLimparClientes;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JButton jButtonPesquisarCliente;
    private javax.swing.JButton jButtonSalvarClientes;
    private javax.swing.JButton jButtonVoltarTelaCliente;
    private javax.swing.JComboBox jComboBoxEstadoCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEPCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPFCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumeroCasa;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelCliente;
    private javax.swing.JLabel jLabel3ComplementoCliente;
    private javax.swing.JLabel jLabelBairroCliente;
    private javax.swing.JLabel jLabelCEPCliente;
    private javax.swing.JLabel jLabelCPFCliente;
    private javax.swing.JLabel jLabelCidadeCliente;
    private javax.swing.JLabel jLabelEmailCliente;
    private javax.swing.JLabel jLabelEnderecoCliente;
    private javax.swing.JLabel jLabelEstadoCliente;
    private javax.swing.JLabel jLabelFinanceiro;
    private javax.swing.JLabel jLabelFundoCliente;
    private javax.swing.JLabel jLabelIDCliente;
    private javax.swing.JLabel jLabelInformacoesPessoais;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNumeroCasaCliente;
    private javax.swing.JLabel jLabelRuaCliente;
    private javax.swing.JLabel jLabelSomaDosValores;
    private javax.swing.JLabel jLabelTelCliente;
    private javax.swing.JLabel jLabelValorAtual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldBairroCliente;
    private javax.swing.JTextField jTextFieldCidadeCliente;
    private javax.swing.JTextField jTextFieldComplementeCliente;
    private javax.swing.JTextField jTextFieldEmailCliente;
    private javax.swing.JTextField jTextFieldIDCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPesquisarCliente;
    private javax.swing.JTextField jTextFieldRuaCliente;
    private javax.swing.JTextField jTextFieldSomaDosValores;
    private javax.swing.JTextField jTextFieldValorAtual;
    private javax.swing.JTextField jTextFieldValorDebitarCreditar;
    // End of variables declaration//GEN-END:variables
}
