/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansProduto;
import modeloBeans.ModeloTabela;
import modeloConnection.ConexaoBD;
import modeloDao.DaoProduto;

/**
 *
 * @author abdias.neto
 */
public class TelaReduzirEstoque extends javax.swing.JFrame {

    BeansProduto mod = new BeansProduto();
    ConexaoBD conex = new ConexaoBD();
    DaoProduto control = new DaoProduto();
    
    /**
     * Creates new form TelaReduzirEstoque
     */
    public TelaReduzirEstoque() {
        initComponents();
        
        jTextFieldIDproduto.setEnabled(false);
        jTextFieldNomeProduto.setEnabled(false);
        jTextFieldPesquisarProduto.setEnabled(true);
        jSpinnerQuantidadeProduto.setEnabled(false);
        
        jButtonPesquisaProduto.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonSair.setEnabled(true);
        
        preencherTabelaAlterarQuantidadeEstoque("select *from estoqueproduto order by nomeproduto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutosComQuantidade = new javax.swing.JTable();
        jLabelReduzirEstoque = new javax.swing.JLabel();
        jLabelIdProduto = new javax.swing.JLabel();
        jLabelNomeProduto = new javax.swing.JLabel();
        jLabelQuantidadeProduto = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonPesquisaProduto = new javax.swing.JButton();
        jTextFieldPesquisarProduto = new javax.swing.JTextField();
        jTextFieldIDproduto = new javax.swing.JTextField();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jSpinnerQuantidadeProduto = new javax.swing.JSpinner();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HA gerencia");
        getContentPane().setLayout(null);

        jTableProdutosComQuantidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProdutosComQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosComQuantidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutosComQuantidade);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 82, 410, 380);

        jLabelReduzirEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produtoEstoque_1.png"))); // NOI18N
        getContentPane().add(jLabelReduzirEstoque);
        jLabelReduzirEstoque.setBounds(90, 10, 70, 80);

        jLabelIdProduto.setText("ID:");
        getContentPane().add(jLabelIdProduto);
        jLabelIdProduto.setBounds(10, 170, 40, 30);

        jLabelNomeProduto.setText("Nome:");
        getContentPane().add(jLabelNomeProduto);
        jLabelNomeProduto.setBounds(10, 220, 50, 30);

        jLabelQuantidadeProduto.setText("Quantidade:");
        getContentPane().add(jLabelQuantidadeProduto);
        jLabelQuantidadeProduto.setBounds(10, 270, 80, 30);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(20, 410, 50, 50);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(170, 410, 50, 50);

        jButtonPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButtonPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisaProduto);
        jButtonPesquisaProduto.setBounds(280, 10, 70, 60);

        jTextFieldPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisarProduto);
        jTextFieldPesquisarProduto.setBounds(360, 40, 270, 30);
        getContentPane().add(jTextFieldIDproduto);
        jTextFieldIDproduto.setBounds(60, 170, 170, 30);
        getContentPane().add(jTextFieldNomeProduto);
        jTextFieldNomeProduto.setBounds(60, 220, 170, 30);
        getContentPane().add(jSpinnerQuantidadeProduto);
        jSpinnerQuantidadeProduto.setBounds(140, 270, 90, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_com_degrade.jpeg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-10, -10, 740, 560);

        setSize(new java.awt.Dimension(674, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        TelaCliente telaCliente = new TelaCliente();
        
        telaCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaProdutoActionPerformed
        mod.setPesquisaProduto(jTextFieldPesquisarProduto.getText());
        BeansProduto model = control.BuscaProduto(mod);
        jTextFieldIDproduto.setText(String.valueOf(model.getIdProduto()));
        jTextFieldNomeProduto.setText(model.getNomeProduto());
        jSpinnerQuantidadeProduto.setValue(model.getQuantidadeProduto());
        
        jTextFieldIDproduto.setEnabled(false);
        jTextFieldNomeProduto.setEnabled(false);
        jSpinnerQuantidadeProduto.setEnabled(true);
        
        jButtonSalvar.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonPesquisaProduto.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisaProdutoActionPerformed

    private void jTableProdutosComQuantidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosComQuantidadeMouseClicked
        String nomeproduto = "" + jTableProdutosComQuantidade.getValueAt(jTableProdutosComQuantidade.getSelectedRow(), 1);
        
        try {
            jTextFieldPesquisarProduto.setText(nomeproduto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados\nErro: " + ex);
        }
        
        jButtonPesquisaProduto.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        
        preencherTabelaAlterarQuantidadeEstoque("select *from estoqueproduto order by nomeproduto");
    }//GEN-LAST:event_jTableProdutosComQuantidadeMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        mod.setQuantidadeProduto((int) jSpinnerQuantidadeProduto.getValue());
        control.atualizaQuantidadeProduto(mod);
        
        jTextFieldIDproduto.setText("");
        jTextFieldNomeProduto.setText("");
        jSpinnerQuantidadeProduto.setValue(0);
        jTextFieldPesquisarProduto.setText("");
        
        jButtonPesquisaProduto.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonSair.setEnabled(true);
        
        TelaCliente telaCliente = new TelaCliente();
        telaCliente.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarProdutoActionPerformed

    public void preencherTabelaAlterarQuantidadeEstoque(String Sql){
        
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Tamanho", "Quantidade"};
        conex.conecta();
        conex.executaSql(Sql);
        
        try {
            conex.rs.first();
            do{
                dados.add(new Object[] {conex.rs.getInt("idproduto"), conex.rs.getString("nomeproduto"), 
                    conex.rs.getString("tamanhoproduto"), conex.rs.getInt("quantidadeproduto")});
                
            }while(conex.rs.next());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList\n erro: " + ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableProdutosComQuantidade.setModel(modelo);
        jTableProdutosComQuantidade.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableProdutosComQuantidade.getColumnModel().getColumn(0).setResizable(false);
        jTableProdutosComQuantidade.getColumnModel().getColumn(1).setPreferredWidth(174);
        jTableProdutosComQuantidade.getColumnModel().getColumn(1).setResizable(false);
        jTableProdutosComQuantidade.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTableProdutosComQuantidade.getColumnModel().getColumn(2).setResizable(false);
        jTableProdutosComQuantidade.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableProdutosComQuantidade.getColumnModel().getColumn(3).setResizable(false);
        jTableProdutosComQuantidade.getTableHeader().setReorderingAllowed(false);
        jTableProdutosComQuantidade.setAutoResizeMode(jTableProdutosComQuantidade.AUTO_RESIZE_OFF);
        jTableProdutosComQuantidade.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
                
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaReduzirEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaReduzirEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaReduzirEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaReduzirEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaReduzirEstoque().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisaProduto;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelIdProduto;
    private javax.swing.JLabel jLabelNomeProduto;
    private javax.swing.JLabel jLabelQuantidadeProduto;
    private javax.swing.JLabel jLabelReduzirEstoque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerQuantidadeProduto;
    private javax.swing.JTable jTableProdutosComQuantidade;
    private javax.swing.JTextField jTextFieldIDproduto;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldPesquisarProduto;
    // End of variables declaration//GEN-END:variables
}
